### ISSUE TITLE
Any plan to migrate to the new guru tool?

### ISSUE THREAD

**Issue by jostyee** [waigani/GoOracle#24]
As _Alan Dodovan_ said in [Upcoming changes in golang.org/x/tools](https://docs.google.com/document/d/1IIjEhq54T5KZHTdSyquMhaQ58htYclQpFEX4WRVOhJw/view#heading=h.y2yf1miyweis) the `oracle` tool will be renamed to `guru` , and there are already some commits to the new package now.

**Comment by kzap** [comment]
https://packagecontrol.io/packages/GoGuru

**Comment by jostyee** [comment]
Thanks @kzap , it helps.
